//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerInquiry.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    [JsonObject(IsReference = false)]
    public partial class Transaction
    {
        public virtual Customer Customer { get; set; }

        public long Transaction_ID { get; set; }
        public long Customer_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Currency_Code { get; set; }
        public string Status { get; set; }
    
    }
}
